### ISSUE TITLE
The function sendMessage's arguments are not exhaustive.

### ISSUE THREAD

**Issue by surafelfikru** [iCog-Haskell/haskell-telegram-bot#8]
`
![Screenshot (8)](https://user-images.githubusercontent.com/74018199/234960337-a036de01-6fbf-4507-9719-a47d92c4388e.png)

It currently only accepts message and chatID. Its better to use the Args type and accept all the arguments as a Map that will validate against the Validator type.

**Comment by kenenisa** [comment]
I know. I was testing it in ghci that's why i changed it to only message and chatID. Fixed the issue with [this commit.](https://github.com/iCog-Haskell/haskell-telegram-bot/commit/4af4892f504c8ece74782092a8e86347e1dda0fb)

**Comment by kenenisa** [comment]
`entities` and `reply_markup` need some work. They are used in many functions so we should build some abstraction.
